### ISSUE TITLE
ActionView::Template::Error (undefined method `bootstrap_load_module'

### ISSUE THREAD

**Issue by reds-heig** [jbox-web/redmine_bootstrap_kit#5]
Hi,

I have the above mentioned error in production.log when using the devel version of your plugin and I try to see the user's details -- as an admin, I click on a name in the list of users. The full log is:

```
Started GET "/users/3/edit" for 127.0.0.1 at 2015-03-31 08:23:55 +0200
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"3"}
  Current user: admin (id=1)
  Rendered users/_mail_notifications.html.erb (11.4ms)
  Rendered users/_preferences.html.erb (186.6ms)
  Rendered users/_form.html.erb (246.5ms)
  Rendered users/_general.html.erb (252.0ms)
  Rendered principal_memberships/_index.html.erb (13.5ms)
  Rendered users/_memberships.html.erb (17.7ms)
  Rendered plugins/redmine_git_hosting/app/views/gitolite_public_keys/_ssh_keys.html.erb (100.6ms)
  Rendered plugins/redmine_git_hosting/app/views/gitolite_public_keys/_view.html.erb (104.0ms)
  Rendered common/_tabs.html.erb (384.3ms)
  Rendered users/edit.html.erb within layouts/admin (391.0ms)
Completed 500 Internal Server Error in 424ms (ActiveRecord: 4.8ms)

ActionView::Template::Error (undefined method `bootstrap_load_module' for #<#<Class:0x000000024eebf0>:0x00000005e073b0>):
    1: <% content_for :header_tags do %>
    2:   <%= bootstrap_load_module(:font_awesome) %>
    3: <% end %>
    4: 
    5: <table class="list">
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___4482561874930778843_14645740'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___4482561874930778843_14645740'
  app/helpers/application_helper.rb:321:in `render_tabs'
  app/views/users/edit.html.erb:10:in `_app_views_users_edit_html_erb___1147500406985825637_49157980'
```

It seems that I can look at an user own setting (if I click on "My account"), but again, if I try to add a new user, I get

```
Started POST "/users" for 127.0.0.1 at 2015-03-31 08:28:52 +0200
Processing by UsersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"mpTD3OwzlPdTLJjcUm/ZcHUoyoZ8LXpIZS0X++VDCecIraypfhqARjbV82FeC+qGW/jHI31tEK1NM/FzAoGoxg==", "user"=>{"login"=>"aaa", "firstname"=>"fff", "lastname"=>"eee", "mail"=>"eee@gg.com", "language"=>"en", "admin"=>"0", "auth_source_id"=>"", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "generate_password"=>"[FILTERED]", "must_change_passwd"=>"0", "mail_notification"=>"only_my_events", "notified_project_ids"=>[""]}, "pref"=>{"no_self_notified"=>"0", "hide_mail"=>"0", "time_zone"=>"", "comments_sorting"=>"asc", "warn_on_leaving_unsaved"=>"1"}, "commit"=>"Create"}
  Current user: admin (id=1)
WARNING: Can't mass-assign protected attributes for User: login
    lib/redmine/safe_attributes.rb:84:in `safe_attributes='
    app/controllers/users_controller.rb:89:in `create'
Redirected to http://10.192.53.152/users/4/edit
Completed 302 Found in 65ms (ActiveRecord: 7.0ms)
Started GET "/users/4/edit" for 127.0.0.1 at 2015-03-31 08:28:52 +0200
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"4"}
  Current user: admin (id=1)
  Rendered users/_mail_notifications.html.erb (9.5ms)
  Rendered users/_preferences.html.erb (11.9ms)
  Rendered users/_form.html.erb (38.2ms)
  Rendered users/_general.html.erb (39.8ms)
  Rendered principal_memberships/_index.html.erb (1.8ms)
  Rendered users/_memberships.html.erb (2.0ms)
  Rendered plugins/redmine_git_hosting/app/views/gitolite_public_keys/_ssh_keys.html.erb (156.0ms)
  Rendered plugins/redmine_git_hosting/app/views/gitolite_public_keys/_view.html.erb (156.6ms)
  Rendered common/_tabs.html.erb (202.2ms)
  Rendered users/edit.html.erb within layouts/admin (207.0ms)
Completed 500 Internal Server Error in 218ms (ActiveRecord: 3.6ms)

ActionView::Template::Error (undefined method `bootstrap_load_module' for #<#<Class:0x000000024eebf0>:0x00000005281130>):
    1: <% content_for :header_tags do %>
    2:   <%= bootstrap_load_module(:font_awesome) %>
    3: <% end %>
    4: 
    5: <table class="list">
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___4482561874930778843_14645740'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___4482561874930778843_14645740'
  app/helpers/application_helper.rb:321:in `render_tabs'
  app/views/users/edit.html.erb:10:in `_app_views_users_edit_html_erb___1147500406985825637_49157980'
```

Here's my config:

```
Environment:
  Redmine version                3.0.1.stable.14155
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_bootstrap_kit          0.2-devel
  redmine_ckeditor               1.1.0
  redmine_code_review            0.0.1
  redmine_git_hosting            1.0-devel
  redmine_issue_templates        0.1.0
  redmine_ldap_sync              2.0.5.devel.ge41aedfa0b
  redmine_private_wiki           0.2.2
  redmine_stats                  0.0.2
  redmine_xls_export             0.2.1.t8
```

Can you help me, please? Thanks a lot in advance!
Rob

**Comment by n-rodriguez** [comment]
Actually this is a Redmine Git Hosting bug. Fixed in commit : https://github.com/jbox-web/redmine_git_hosting/commit/275c1bc36dfb1b248693d348db6ed27b6abe00c2

**Comment by reds-heig** [comment]
It works!!
Sorry for the mistake...
Have a nice day!
Rob
