### ISSUE TITLE
Does not work with Redmine 3.0.2

### ISSUE THREAD

**Issue by wilful** [jbox-web/redmine_bootstrap_kit#6]
wanted to upgrade, but nothing happened.
With version 3.0.1 works fine.

```
redmine-3.0.2]# bundle exec rake redmine:plugins:migrate RAILS_ENV=production                                                                                                                [175/2455]
rake aborted!
NameError: Couldn't find RedmineBootstrapKitHelper, expected it to be defined in     helpers/redmine_bootstrap_kit_helper.rb
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-    4.2.1/lib/abstract_controller/helpers.rb:162:in `rescue in block in modules_for_helpers'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:155:in `block in modules_for_helpers'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:144:in `map!'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-  4.2.1/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
```

etc

**Comment by n-rodriguez** [comment]
Do you have other plugins installed?

**Comment by wilful** [comment]
Yes, i have a couple plugins

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/redmine_git_hosting/issues/498
