### ISSUE TITLE
migrate fails with redmine 3.0.3

### ISSUE THREAD

**Issue by Tcharl** [jbox-web/redmine_bootstrap_kit#7]
Hi,

I've got this error trying to install your plugin:

```
rake aborted!
LoadError: No such file to load -- will_paginate/view_helpers/action_view
/usr/share/redmine/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/share/redmine/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/redmine/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/redmine/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/share/redmine/plugins/redmine_bootstrap_kit/app/helpers/bootstrap/will_paginate_helper.rb:1:in `<top (required)>'
/usr/share/redmine/vendor/bundle/ruby/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
```

I'm not a ruby afficionados, so I can only help in testing.

Best regards,
Charlie

**Comment by tostasqb** [comment]
+1

**Comment by speedy32129** [comment]
I got the same issue and I have the same version however I got it to work by running "bundle install"  as a gem will_paginate was missing.

Hope that helps.
